name: pytorch-nst
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.8
  - pip=20.0.2
  - matplotlib=3.1.3
  - pytorch==1.12.1
  - torchvision==0.13.1
  - pip:
    - numpy==1.18.1
    - opencv-python==4.2.0.32
    - ipykernel