name: pytorch-nst
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.8
  - pip=20.0.2
  - matplotlib=3.1.3
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu116
    - torch==1.13.0+cu116
    - torchvision==0.14.0+cu116
    - torchaudio==0.13.0
    - numpy==1.18.1
    - opencv-python==4.2.0.32
    - ipykernel